import { Inria_Sans } from "next/font/google";
import "./globals.css";

const inriaSans = Inria_Sans({
  subsets: ['latin'], 
  display: 'swap', 
  weight: '700',
  variable: '--font-inria-sans',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inriaSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
